version: 2.1
# https://circleci.com/docs/2.0/sample-config/

orbs:
  heroku: circleci/heroku@1.1.1 # Use the Heroku orb in your config

workflows:
  deploy_to_heroku:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - hold
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8-stretch-node
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: mkdir test_reports
  test:
    steps:
      - run:
        name: unit tests & codecov
        command: |
          source .env/bin/activate
          python -m pytest --cov=app1 --cov-report=xml --junitxml=test_reports/junit.xml
          python -m codecov --token=5116b8f0-c09b-482b-b494-5fd66df4f6b3
      - store_artifacts:
          path: test_reports/
      - store_test_results:
          path: test_reports/
      - prepare_heroku:
          name: Prepare Heroku deployment
          command: |
            export HEROKU_APP_NAME=loi-flask
            export HEROKU_API_KEY=07ddad3a-9ac9-433e-94fc-79cb1ef0d7ed

# Orchestrate our job run sequence. Approval Job
# The build job runs, then the test job, then a hold job, with type: approval ensures the workflow waits for manual approval before the deploy job can run.
