version: 2
# https://circleci.com/docs/2.0/sample-config/
# https://circleci.com/docs/2.0/configuration-reference/
jobs:
  build_test:
    # executor: python/default
    docker:
      - image: circleci/python:3.7.8-stretch-node
        environment:
          AUTHOR: Tran-Duc-Loi
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install deps
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: mkdir -p test_reports
          name: Make test_reports
      - run:
          command: |
            source venv/bin/activate
            python -m pytest --cov=app1 --cov-report=xml --junitxml=test_reports/junit.xml
            python -m codecov --token=$CODECOV_TOKEN
          name: unit tests & codecov
      - store_artifacts:
          path: test_reports/
      - store_test_results:
          path: test_reports/
  deploy:
    docker:
      - image: circleci/python:3.7.8-stretch-node
    steps:
      - checkout
      - run:
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          name: Deploy to heroku
workflows:
  version: 2
  deploy_to_heroku:
    jobs:
      - build_test
      # - hold:
      #     type: approval
      #     requires:
      #       - build_test
      - deploy:
          requires:
            - build_test
            # - hold
          filters:
            branches:
              only: master