"""init

Revision ID: dadb312e05e9
Revises: 
Create Date: 2020-08-05 11:37:26.336862

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'dadb312e05e9'
down_revision = None
branch_labels = None
depends_on = None

def add_seed():
    tbl_roles = sa.sql.table( 'tbl_roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True)
    )
    
    tbl_users = sa.sql.table('tbl_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=500), nullable=True),
        sa.Column('fullname', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('authtype', sa.Integer(), nullable=False),
        sa.Column('created_date', sa.DateTime(timezone=True), nullable=False, default=datetime.utcnow),
        sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False, default=datetime.utcnow)
    )
    
    tbl_user_role = sa.sql.table('tbl_user_role',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_email', sa.String(length=255), nullable=False),
        sa.Column('role_role', sa.String(length=255), nullable=False)
    )
    
    op.bulk_insert(
        tbl_roles,
        [
            {'role':'admin', 'description': 'Administrator'},
            {'role':'user', 'description': 'Normal User'}
        ]        
    )
    
    op.bulk_insert(
        tbl_users,
        [
            {'email':'admin@myflask.com', 'password':"pbkdf2:sha256:150000$8MeWtFuN$22dd4d822ec9bc71d16841579a2bf4de92f2e2c3581341181627f7f96b03a647",'fullname':"Admin", 'status':1, 'authtype':0},
            {'email':'user@myflask.com',  'password':"pbkdf2:sha256:150000$8MeWtFuN$22dd4d822ec9bc71d16841579a2bf4de92f2e2c3581341181627f7f96b03a647",'fullname':"User",  'status':1, 'authtype':0}
        ]        
    )
    
    op.bulk_insert(
        tbl_user_role,
        [
            {'user_email':'admin@myflask.com', 'role_role': 'admin'},
            {'user_email':'user@myflask.com',  'role_role': 'user'},
            # {'user_email':'loitd@myflask.com', 'role_role': 'test'}
        ]        
    )


def upgrade():
    # For a clean init
    op.drop_table('tbl_user_role')
    op.drop_table('tbl_users')
    op.drop_table('tbl_roles')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('authtype', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False, default=datetime.utcnow),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False, default=datetime.utcnow),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tbl_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('role_role', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['role_role'], ['tbl_roles.role'], ),
    sa.ForeignKeyConstraint(['user_email'], ['tbl_users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    add_seed()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user_role')
    op.drop_table('tbl_users')
    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
